/**
 * GENERATED FILE — do not edit.
 *
 * Source: server/openapi.json, itself derived from the muorg-server route
 * handlers. Regenerate with ./scripts/generate-api-clients.sh after any API
 * change; CI fails if this file is stale.
 */
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/backup-directory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Where pre-write backups are kept on the server. */
        get: operations["get_backup_directory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/clear-cache": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Purge soft-deleted rows immediately. */
        post: operations["clear_cache"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deeper health check than `/api/health`: also proves the catalog is readable. */
        get: operations["admin_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Prometheus exposition format. */
        get: operations["admin_metrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/remove-folder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Drop a root and soft-delete the tracks under it. */
        post: operations["remove_folder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/rescan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Rescan one root, or every root when no body is sent. */
        post: operations["rescan"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Chromecast devices seen by the current mDNS sweep. */
        get: operations["cast_devices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/discovery/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Begin mDNS discovery. */
        post: operations["cast_start_discovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/discovery/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stop mDNS discovery. */
        post: operations["cast_stop_discovery"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/pause": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Pause the cast session. */
        post: operations["cast_pause"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start casting a track to a device. */
        post: operations["cast_play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/resume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Resume the cast session. */
        post: operations["cast_resume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/seek": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Seek within the casting track. */
        post: operations["cast_seek"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current cast session state and device volume. */
        get: operations["cast_status"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/stop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tear down the cast session. */
        post: operations["cast_stop"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cast/volume": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set device volume, 0.0–1.0. */
        post: operations["cast_set_volume"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/fetch-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Proxy-fetch a remote image and return it base64-encoded, so the clients can
         *     pull cover art from the web without tripping CORS.
         */
        post: operations["fetch_image"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Unauthenticated liveness probe. */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/play-history/recent": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_recent_play_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/play-history/top": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_top_play_history"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All playlists, in user-defined order. */
        get: operations["list_playlists"];
        put?: never;
        /** Create an empty playlist. */
        post: operations["create_playlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a playlist and its entries. */
        delete: operations["delete_playlist"];
        options?: never;
        head?: never;
        /** Rename a playlist and/or set its icon. */
        patch: operations["update_playlist"];
        trace?: never;
    };
    "/api/playlists/{id}/entries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Playlist entries, which carry their own id so the same track can appear twice. */
        get: operations["get_playlist_entries"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/entries/{entry_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove one entry, leaving other copies of the same track in place. */
        delete: operations["remove_playlist_entry"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Track ids in playlist order. */
        get: operations["get_playlist_tracks"];
        put?: never;
        /** Append tracks to a playlist. */
        post: operations["add_playlist_tracks"];
        /** Remove every entry for the given tracks. */
        delete: operations["remove_playlist_tracks"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/{id}/tracks/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder entries within a playlist. */
        put: operations["reorder_playlist_tracks"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/order": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Reorder the playlists themselves. */
        put: operations["reorder_playlists"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/smart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a rule-driven smart playlist. */
        post: operations["create_smart_playlist"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/playlists/smart/{id}/rules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Replace a smart playlist's rule set. */
        patch: operations["update_smart_playlist_rules"];
        trace?: never;
    };
    "/api/playlists/smart/{id}/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Evaluate the rules and return the matching track ids. */
        get: operations["get_smart_playlist_tracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/roots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_roots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["search_tracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_stats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_tracks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/auto-tag-suggestions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** MusicBrainz candidates for this track. With no body, the query is built from the file\u2019s own tags. */
        post: operations["auto_tag_suggestions"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/backup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The most recent pre-write backup of this file, if one exists. */
        get: operations["get_backup"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/cover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Embedded album art, optionally downscaled. */
        get: operations["get_cover"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/lyrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_lyrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/metadata": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tags read straight off the file, including album art and ReplayGain. */
        get: operations["get_metadata"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Write tags back to the file. Absent fields are left alone, `null` clears the tag. */
        patch: operations["patch_metadata"];
        trace?: never;
    };
    "/api/tracks/{id}/play": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record a play. Bumps `play_count`/`last_played_at` and appends to play history. */
        post: operations["record_play"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set or clear the 1–5 star rating. */
        post: operations["set_rating"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/rename": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move the file on disk and repoint the catalog row. */
        post: operations["rename_file"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Restore the file from its most recent backup. */
        post: operations["restore_backup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/{id}/stream-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Mint a short-lived (8h) token for the public `/stream/{id}` URL, so an
         *     `<audio src>` can play without carrying the API key.
         */
        get: operations["issue_token"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Total track count without loading rows. */
        get: operations["get_tracks_count"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/metadata/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Apply a metadata patch to many tracks in one call. */
        post: operations["batch_patch_metadata"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/tracks/recently-added": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_recently_added"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stream/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audio bytes, range-capable. Public: authorised by the `token` query
         *     parameter rather than the Bearer header, so browsers and cast receivers can
         *     fetch it directly.
         */
        get: operations["stream_audio"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description `GET /api/admin/health` */
        AdminHealthResponse: {
            server: string;
            /** @description `"ok"` when the catalog is readable, `"degraded"` otherwise. */
            status: string;
            version: string;
        };
        /** @description `POST /api/tracks/{id}/auto-tag-suggestions` */
        AutoTagSuggestionsResponse: {
            candidates: components["schemas"]["MatchCandidate"][];
        };
        /** @description `GET /api/admin/backup-directory` */
        BackupDirectoryResponse: {
            path: string;
        };
        BatchMetadataItem: components["schemas"]["MetadataUpdate"] & {
            /** Format: int64 */
            id: number;
        };
        /** @description `POST /api/tracks/metadata/batch` */
        BatchUpdateResponse: {
            ok: boolean;
            /** @description Number of tracks whose tags were actually written. */
            updated: number;
        };
        CastDevice: {
            address: string;
            id: string;
            name: string;
            /** Format: int32 */
            port: number;
        };
        CastSessionStatus: {
            /** @enum {string} */
            status: "idle";
        } | {
            /** @enum {string} */
            status: "connecting";
        } | {
            /** @enum {string} */
            status: "transcoding";
        } | {
            /** Format: float */
            position_secs?: number | null;
            /** @enum {string} */
            status: "playing";
        } | {
            /** Format: float */
            position_secs?: number | null;
            /** @enum {string} */
            status: "paused";
        } | {
            finished: boolean;
            /** @enum {string} */
            status: "stopped";
        } | {
            message: string;
            /** @enum {string} */
            status: "error";
        };
        CastStatusResponse: {
            session: components["schemas"]["CastSessionStatus"];
            /** Format: float */
            volume: number;
        };
        CatalogTrack: {
            album?: string | null;
            album_artist?: string | null;
            artist?: string | null;
            /** Format: int64 */
            disc_number?: number | null;
            /** Format: int64 */
            duration_secs?: number | null;
            featuring?: string | null;
            format: string;
            genre?: string | null;
            has_cover: boolean;
            /** Format: int64 */
            id: number;
            /** Format: int64 */
            last_played_at?: number | null;
            /** Format: int64 */
            mtime_secs: number;
            path: string;
            /** Format: int64 */
            play_count: number;
            /** Format: int64 */
            rating?: number | null;
            /** Format: int64 */
            root_id: number;
            title?: string | null;
            /** Format: int64 */
            track_number?: number | null;
            /** Format: int64 */
            year?: number | null;
        };
        /** @description `GET /api/tracks/count` */
        CountResponse: {
            /** Format: int64 */
            count: number;
        };
        CreateBody: {
            name: string;
        };
        /** @description Body of every non-2xx response. */
        ErrorResponse: {
            error: string;
        };
        FetchedImage: {
            base64: string;
            mime: string;
        };
        FetchImageBody: {
            url: string;
        };
        LibraryStats: {
            /** Format: int64 */
            album_count: number;
            /** Format: int64 */
            artist_count: number;
            /** Format: int64 */
            total_duration_secs: number;
            /** Format: int64 */
            track_count: number;
        };
        /** @description A single candidate match from MusicBrainz. */
        MatchCandidate: {
            album?: string | null;
            album_artist?: string | null;
            artist: string;
            /**
             * Format: double
             * @description Confidence score 0.0–1.0 computed by comparing query against results.
             */
            confidence: number;
            /** @description MusicBrainz recording MBID. */
            mbid: string;
            title: string;
            /** Format: int32 */
            track_number?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        /**
         * @description Patch document for `PATCH /api/tracks/{id}/metadata`.
         *
         *     Every field is `Option<Option<T>>`: absent means "leave this tag alone",
         *     `null` means "clear it". `ToSchema` flattens that to a plain nullable
         *     optional, which is the right shape for a JSON patch body.
         */
        MetadataUpdate: {
            album?: string | null;
            album_artist?: string | null;
            artist?: string | null;
            /** Format: int32 */
            disc_number?: number | null;
            featuring?: string | null;
            genre?: string | null;
            picture_base64?: string | null;
            title?: string | null;
            /** Format: int32 */
            track_number?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        /** @description The uniform acknowledgement for mutations that return no data. */
        OkResponse: {
            /** @description Always `true`; failures come back as an [`ErrorResponse`] with a 4xx/5xx. */
            ok: boolean;
        };
        PatchMetadataBody: components["schemas"]["MetadataUpdate"] & {
            backup_before_write?: boolean | null;
        };
        PlayBody: {
            device_address: string;
            /** Format: int32 */
            device_port: number;
            /** Format: int64 */
            track_id: number;
        };
        Playlist: {
            icon?: string | null;
            /** Format: int64 */
            id: number;
            name: string;
            smart_rules?: string | null;
            /** Format: int64 */
            track_count: number;
        };
        PlaylistTrackEntry: {
            /** Format: int64 */
            entry_id: number;
            /** Format: int64 */
            track_id: number;
        };
        RatingBody: {
            /** Format: int64 */
            rating?: number | null;
        };
        RemoveFolderBody: {
            root_path: string;
        };
        RenameBody: {
            new_path: string;
        };
        ReorderBody: {
            ids: number[];
        };
        RescanBody: {
            root_path?: string | null;
        };
        RescanResult: {
            /** Format: int64 */
            tracks_added: number;
        };
        /** @description Query parameters for searching MusicBrainz. */
        SearchQuery: {
            album?: string | null;
            artist?: string | null;
            /** Format: int32 */
            duration_secs?: number | null;
            title?: string | null;
        };
        SeekBody: {
            /** Format: float */
            position_secs: number;
            was_playing: boolean;
        };
        SmartCreateBody: {
            name: string;
            rules_json: string;
        };
        SmartRulesBody: {
            rules_json: string;
        };
        TokenResponse: {
            token: string;
        };
        TrackBackupRecord: {
            backup_path: string;
            /** Format: int64 */
            created_at: number;
            /** Format: int64 */
            id: number;
            track_path: string;
        };
        TrackIdsBody: {
            track_ids: number[];
        };
        /** @description Stored lyrics for a track, if any. */
        TrackLyrics: {
            lyrics: string;
            sync_format: string;
            /** Format: int64 */
            track_id: number;
        };
        TrackMetadata: {
            album?: string | null;
            album_artist?: string | null;
            artist?: string | null;
            /** Format: int32 */
            disc_number?: number | null;
            /** Format: int64 */
            duration_secs?: number | null;
            featuring?: string | null;
            genre?: string | null;
            /** @description Embedded lyrics text (USLT / UNSYNCEDLYRICS, or synced when available). */
            lyrics?: string | null;
            /**
             * @description `"lrc"` when the lyrics text carries `[mm:ss.xx]` timing lines, else
             *     `"plain"`. Absent when there are no embedded lyrics.
             */
            lyrics_format?: string | null;
            picture_base64?: string | null;
            picture_mime?: string | null;
            /** Format: int32 */
            picture_size_bytes?: number | null;
            /** Format: float */
            replaygain_album_gain_db?: number | null;
            /** Format: float */
            replaygain_album_peak?: number | null;
            /** Format: float */
            replaygain_track_gain_db?: number | null;
            /** Format: float */
            replaygain_track_peak?: number | null;
            title?: string | null;
            /** Format: int32 */
            track_number?: number | null;
            /** Format: int32 */
            year?: number | null;
        };
        UpdateBody: {
            icon?: string | null;
            name?: string | null;
        };
        VolumeBody: {
            /** Format: float */
            level: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type SchemaAdminHealthResponse = components['schemas']['AdminHealthResponse'];
export type SchemaAutoTagSuggestionsResponse = components['schemas']['AutoTagSuggestionsResponse'];
export type SchemaBackupDirectoryResponse = components['schemas']['BackupDirectoryResponse'];
export type SchemaBatchMetadataItem = components['schemas']['BatchMetadataItem'];
export type SchemaBatchUpdateResponse = components['schemas']['BatchUpdateResponse'];
export type SchemaCastDevice = components['schemas']['CastDevice'];
export type SchemaCastSessionStatus = components['schemas']['CastSessionStatus'];
export type SchemaCastStatusResponse = components['schemas']['CastStatusResponse'];
export type SchemaCatalogTrack = components['schemas']['CatalogTrack'];
export type SchemaCountResponse = components['schemas']['CountResponse'];
export type SchemaCreateBody = components['schemas']['CreateBody'];
export type SchemaErrorResponse = components['schemas']['ErrorResponse'];
export type SchemaFetchedImage = components['schemas']['FetchedImage'];
export type SchemaFetchImageBody = components['schemas']['FetchImageBody'];
export type SchemaLibraryStats = components['schemas']['LibraryStats'];
export type SchemaMatchCandidate = components['schemas']['MatchCandidate'];
export type SchemaMetadataUpdate = components['schemas']['MetadataUpdate'];
export type SchemaOkResponse = components['schemas']['OkResponse'];
export type SchemaPatchMetadataBody = components['schemas']['PatchMetadataBody'];
export type SchemaPlayBody = components['schemas']['PlayBody'];
export type SchemaPlaylist = components['schemas']['Playlist'];
export type SchemaPlaylistTrackEntry = components['schemas']['PlaylistTrackEntry'];
export type SchemaRatingBody = components['schemas']['RatingBody'];
export type SchemaRemoveFolderBody = components['schemas']['RemoveFolderBody'];
export type SchemaRenameBody = components['schemas']['RenameBody'];
export type SchemaReorderBody = components['schemas']['ReorderBody'];
export type SchemaRescanBody = components['schemas']['RescanBody'];
export type SchemaRescanResult = components['schemas']['RescanResult'];
export type SchemaSearchQuery = components['schemas']['SearchQuery'];
export type SchemaSeekBody = components['schemas']['SeekBody'];
export type SchemaSmartCreateBody = components['schemas']['SmartCreateBody'];
export type SchemaSmartRulesBody = components['schemas']['SmartRulesBody'];
export type SchemaTokenResponse = components['schemas']['TokenResponse'];
export type SchemaTrackBackupRecord = components['schemas']['TrackBackupRecord'];
export type SchemaTrackIdsBody = components['schemas']['TrackIdsBody'];
export type SchemaTrackLyrics = components['schemas']['TrackLyrics'];
export type SchemaTrackMetadata = components['schemas']['TrackMetadata'];
export type SchemaUpdateBody = components['schemas']['UpdateBody'];
export type SchemaVolumeBody = components['schemas']['VolumeBody'];
export type $defs = Record<string, never>;
export interface operations {
    get_backup_directory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Absolute backup directory path */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BackupDirectoryResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    clear_cache: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cache cleared */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    admin_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server and catalog status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminHealthResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    admin_metrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Prometheus metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_folder: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RemoveFolderBody"];
            };
        };
        responses: {
            /** @description Root removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rescan: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": null | components["schemas"]["RescanBody"];
            };
        };
        responses: {
            /** @description Scan finished */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RescanResult"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_devices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovered devices */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CastDevice"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_start_discovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery started */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_stop_discovery: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Discovery stopped */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_pause: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_play: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlayBody"];
            };
        };
        responses: {
            /** @description Command accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_resume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_seek: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SeekBody"];
            };
        };
        responses: {
            /** @description Command accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_status: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CastStatusResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_stop: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Command accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    cast_set_volume: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VolumeBody"];
            };
        };
        responses: {
            /** @description Command accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    fetch_image: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FetchImageBody"];
            };
        };
        responses: {
            /** @description Base64 image plus its MIME type */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FetchedImage"];
                };
            };
            /** @description URL unreachable or not an image */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server is up */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/plain": unknown;
                };
            };
        };
    };
    get_recent_play_history: {
        parameters: {
            query?: {
                /** @description Look-back window in days. Default 30. Only used by `/api/play-history/top`. */
                days?: number | null;
                /** @description Rows to return. Default 50. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recently played tracks, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogTrack"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_top_play_history: {
        parameters: {
            query?: {
                /** @description Look-back window in days. Default 30. Only used by `/api/play-history/top`. */
                days?: number | null;
                /** @description Rows to return. Default 50. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most played tracks within the window */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogTrack"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_playlists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Playlists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_playlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateBody"];
            };
        };
        responses: {
            /** @description The created playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_playlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_playlist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateBody"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_playlist_entries: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Entries, in playlist order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlaylistTrackEntry"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_playlist_entry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist entry id */
                entry_id: number;
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_playlist_tracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Track ids, in playlist order */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_playlist_tracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackIdsBody"];
            };
        };
        responses: {
            /** @description Added */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    remove_playlist_tracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TrackIdsBody"];
            };
        };
        responses: {
            /** @description Removed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reorder_playlist_tracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderBody"];
            };
        };
        responses: {
            /** @description Reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reorder_playlists: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReorderBody"];
            };
        };
        responses: {
            /** @description Reordered */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    create_smart_playlist: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmartCreateBody"];
            };
        };
        responses: {
            /** @description The created playlist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Playlist"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    update_smart_playlist_rules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SmartRulesBody"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_smart_playlist_tracks: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Playlist id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching track ids */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": number[];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such playlist */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_roots: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configured library root folders */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    search_tracks: {
        parameters: {
            query: {
                /** @description Free-text query matched against title, artist and album. */
                q: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Matching tracks */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogTrack"][];
                };
            };
            /** @description Missing `q` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_stats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog totals */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LibraryStats"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_tracks: {
        parameters: {
            query?: {
                /**
                 * @description Rows to return. Default 500 — this is the page size every client must
                 *     loop against; a bare `/api/tracks` is page one, not the whole catalog.
                 */
                limit?: number | null;
                /** @description Row to start at. Default 0. */
                offset?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description One page of the catalog. `X-Total-Count` carries the full catalog size, so a client knows how many more pages to fetch. */
            200: {
                headers: {
                    /** @description Total tracks in the catalog */
                    "X-Total-Count"?: number;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogTrack"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    auto_tag_suggestions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchQuery"];
            };
        };
        responses: {
            /** @description Ranked candidates, best first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AutoTagSuggestionsResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_backup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backup record, or null when none exists */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": null | components["schemas"]["TrackBackupRecord"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_cover: {
        parameters: {
            query?: {
                /** @description Requested max edge length in px; when provided the cover is downscaled. */
                size?: number | null;
            };
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Image bytes (JPEG or PNG) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": unknown;
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Track has no embedded cover */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_lyrics: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stored lyrics; `sync_format` is `lrc` for timestamped text, else `plain` */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackLyrics"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Track has no embedded lyrics */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Track tags */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackMetadata"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    patch_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PatchMetadataBody"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    record_play: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    set_rating: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingBody"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    rename_file: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameBody"];
            };
        };
        responses: {
            /** @description Renamed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description Destination invalid or already taken */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    restore_backup: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restored */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
            /** @description No backup to restore */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    issue_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream token */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_tracks_count: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Total tracks in the catalog */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    batch_patch_metadata: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchMetadataItem"][];
            };
        };
        responses: {
            /** @description Number of tracks written */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchUpdateResponse"];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_recently_added: {
        parameters: {
            query?: {
                /** @description Look-back window in days. Default 30. Only used by `/api/play-history/top`. */
                days?: number | null;
                /** @description Rows to return. Default 50. */
                limit?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Most recently scanned tracks, newest first */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CatalogTrack"][];
                };
            };
            /** @description Missing or invalid API key */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_audio: {
        parameters: {
            query?: {
                /** @description Seek offset in seconds; the server transcodes from this point. */
                start?: number | null;
                /** @description Short-lived token from `/api/tracks/{id}/stream-token`. */
                token?: string | null;
            };
            header?: never;
            path: {
                /** @description Track id */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audio bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "audio/mpeg": unknown;
                };
            };
            /** @description Partial content for a ranged request */
            206: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing, expired or wrong token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No such track */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
