/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        sans: ["system-ui", "sans-serif"],
      },
      colors: {
        primary: "var(--primary)",
        "on-primary": "var(--on-primary)",
        "primary-container": "var(--primary-container)",
        "on-primary-container": "var(--on-primary-container)",
        secondary: "var(--secondary)",
        "secondary-container": "var(--secondary-container)",
        "on-secondary-container": "var(--on-secondary-container)",
        tertiary: "var(--tertiary)",
        background: "var(--background)",
        "on-background": "var(--on-background)",
        surface: "var(--surface)",
        "on-surface": "var(--on-surface)",
        "surface-variant": "var(--surface-variant)",
        "on-surface-variant": "var(--on-surface-variant)",
        "surface-container": "var(--surface-container)",
        outline: "var(--outline)",
        error: "var(--error)",
        "on-error": "var(--on-error)",
        "error-container": "var(--error-container)",
        "on-error-container": "var(--on-error-container)",
        accent: "var(--primary)",
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0.5px" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0.25px" }],
        "body-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.4px" }],
        "title-lg": ["22px", { lineHeight: "28px" }],
        "title-md": ["16px", { lineHeight: "24px", letterSpacing: "0.15px" }],
        "title-sm": ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        "label-lg": ["14px", { lineHeight: "20px", letterSpacing: "0.1px" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        "label-sm": ["11px", { lineHeight: "16px", letterSpacing: "0.5px" }],
        "headline-sm": ["24px", { lineHeight: "32px" }],
        "headline-lg": ["32px", { lineHeight: "40px" }],
      },
    },
  },
  plugins: [],
};
